{% set name = "qiskit-optimization" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-optimization-{{ version }}.tar.gz
  sha256: 0ad8c2bc83fe80657c788b5f282ce4055d0ec005c4876789e5069499ee3c00c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=40.1.0
  run:
    - qiskit >=0.44
    - qiskit-algorithms >=0.2.0
    - docplex >=2.21.207,!=2.24.231
    - networkx >=2.6.3
    - numpy >=1.17
    - python >=3.8
    - scipy >=1.9.0
    - setuptools >=40.1.0

test:
  imports:
    - qiskit_optimization
    - qiskit_optimization.algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-optimization
  summary: 'Qiskit Optimization: A library of quantum computing optimizations'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
    - BastianZim
