{% set name = "qiskit-optimization" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-optimization-{{ version }}.tar.gz
  sha256: 4804831e590a7159c2bd2be71750cde0c95a3b06e14a4843346e2ebcc7231e01

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=40.1.0
  run:
    - dataclasses
    - docplex >=2.21.207,!=2.24.231
    - networkx >=2.6.3
    - numpy >=1.17
    - python >=3.7
    - qiskit-terra >=0.22.4
    - scipy >=1.4
    - setuptools >=40.1.0

test:
  imports:
    - qiskit_optimization
    - qiskit_optimization.algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-optimization
  summary: 'Qiskit Optimization: A library of quantum computing optimizations'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
    - BastianZim
