{% set name = "qiskit-optimization" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 059e9329c647534965e68d8c52de1b02828635c525c210aa0730e486f9c5a686

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=40.1.0
  run:
    - qiskit >=1.1,<3
    - qiskit-algorithms >=0.2.0
    - docplex >=2.21.207,!=2.24.231
    - networkx >=2.6.3
    - numpy >=1.17
    - python >={{ python_min }}
    - scipy >=1.9.0
    - setuptools >=40.1.0

test:
  imports:
    - qiskit_optimization
    - qiskit_optimization.algorithms
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qiskit-community/qiskit-optimization
  summary: 'Qiskit Optimization: A library of quantum computing optimizations'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
    - BastianZim
