{% set name = "qiskit-optimization" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-optimization-{{ version }}.tar.gz
  sha256: 76cc839df99ecfa366b3e136a231cee479ec20be948e15bfdaf753d53e96be99

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=40.1.0
  run:
    - dataclasses
    - docplex >=2.21.207
    - networkx >=2.2
    - numpy >=1.17
    - python >=3.7
    - qiskit-terra >=0.19.1
    - scipy >=1.4
    - setuptools >=40.1.0

test:
  imports:
    - qiskit_optimization
    - qiskit_optimization.algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-optimization
  summary: 'Qiskit Optimization: A library of quantum computing optimizations'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
